name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: elixir:1.9-alpine
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apk add --update bash openssl git
          mix local.hex --force && mix local.rebar --force
          mix deps.get

      - name: Run linters and tests
        env:
          MIX_ENV: test
        run: mix ci
